apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
    livenessProbe:
      httpGet:
        path: /actuator/health/liveness # Endpoint liveness probe
        port: 8080
      initialDelaySeconds: 20 # Tunggu 20 detik sebelum cek pertama
      periodSeconds: 10       # Cek setiap 10 detik
      failureThreshold: 3     # Gagal 3 kali berturut-turut baru restart Pod
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness # Endpoint readiness probe
        port: 8080
      initialDelaySeconds: 30 # Tunggu 30 detik sebelum cek pertama (lebih lama dari liveness jika ada inisialisasi)
      periodSeconds: 10       # Cek setiap 10 detik
      failureThreshold: 3     # Gagal 3 kali berturut-turut baru anggap tidak siap
      successThreshold: 1     # Berhasil 1 kali baru anggap siap
volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: my-pvc
