apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
management :
  endpoints:
    web:
      exposure:
        include: "health,info"
    health:
      show-details: "always"