apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin123
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
management :
  endpoints:
    web:
      exposure:
        include: "health,info"
    health:
      show-details: "always"
--- 
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: my-pvc

      containers:
              - name: spring-boot-container
                image: your-registry/your-spring-boot-image:latest
                ports:
                  - containerPort: 8080
                volumeMounts:
                  - name: upload-volume
                    mountPath: /app/uploads  # Lokasi di dalam containevolumes:
              - name: upload-volume
                persistentVolumeClaim:
                  claimName: upload-pvc  # Sesuai nama PVC-mu